version: "3.8"

volumes:
  mariadb_data:

services:
  app:
    image: esmira23/docker-jenkins-pipeline:latest
    container_name: tracking-application
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    ports:
      - 3306:3306
    volumes: 
      - ./mariadb.sql:/docker-entrypoint-initdb.d/mariadb.sql
      - mariadb_data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=0721
      - MYSQL_DATABASE=jiraproject
      # - MYSQL_USER=esmira
      # - MYSQL_PASSWORD=secret
    restart: unless-stopped
      # - MYSQL_HOST_AUTH_METHOD:trust